/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const MessagePayload = IDL.Record({
  'message' : IDL.Text,
  'senderName' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const Submission = IDL.Record({
  'timestamp' : Time,
  'payload' : MessagePayload,
});

export const idlService = IDL.Service({
  'getAllMessages' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'submitMessage' : IDL.Func([MessagePayload], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const MessagePayload = IDL.Record({
    'message' : IDL.Text,
    'senderName' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const Submission = IDL.Record({
    'timestamp' : Time,
    'payload' : MessagePayload,
  });
  
  return IDL.Service({
    'getAllMessages' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'submitMessage' : IDL.Func([MessagePayload], [], []),
  });
};

export const init = ({ IDL }) => { return []; };